# Generated by Django on 2025-12-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("tasks", "0006_taskstatistics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0003_delete_taskstatistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_responses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего ответов"
                    ),
                ),
                (
                    "completed_tasks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершено задач"
                    ),
                ),
                (
                    "pending_tasks",
                    models.PositiveIntegerField(default=0, verbose_name="В процессе"),
                ),
                (
                    "survey_stats",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Статистика анкет"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_statistics_tasks",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "client_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.clientgroup",
                        verbose_name="Группа клиентов",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "EMPLOYEE"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "MODERATOR"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика задачи",
                "verbose_name_plural": "Статистика задач",
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name="taskstatistics",
            unique_together={("task", "client", "employee")},
        ),
    ]