# Generated by Django on 2025-12-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_taskstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatistics",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_statistics_tasks",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
    ]