# Generated by Django 6.0 on 2025-12-09 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_surveyanswerphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswerphoto',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='survey_answer_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото'),
        ),
    ]
