# Generated by Django 6.0 on 2025-12-12 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_surveyanswerphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения'),
        ),
        migrations.AlterField(
            model_name='surveyanswerphoto',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='survey_answer_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото'),
        ),
    ]
