# Generated by Django 6.0 on 2025-12-13 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_surveyanswerphoto_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст объявления')),
                ('target_group', models.CharField(choices=[('ALL_USERS', 'Все пользователи'), ('ALL_EMPLOYEES', 'Все сотрудники'), ('MODERATORS', 'Модераторы'), ('SELECTED', 'Выбранные пользователи')], default='SELECTED', max_length=20, verbose_name='Группа получателей')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='Требовать подтверждения прочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Создано модератором')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='tasks.announcement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус прочтения',
                'verbose_name_plural': 'Статусы прочтения',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
