# Generated by Django 5.2.8 on 2025-11-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="target_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Оставьте пустым для '--' (любое количество)",
                null=True,
                verbose_name="План (мин. кол-во заполнений)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("single_select", "Список (один выбор)"),
                    ("multi_select", "Список (множественный выбор)"),
                    ("checkbox", "Чекбоксы (множественный)"),
                    ("radio", "Радиокнопки (один)"),
                    ("photo", "Фото"),
                ],
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
