# Generated by Django 5.2.8 on 2025-11-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_survey_target_count_alter_question_question_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название холдинга"
                    ),
                ),
            ],
            options={
                "verbose_name": "Холдинг",
                "verbose_name_plural": "Холдинги",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surveys.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                max_length=255, verbose_name="ФИО клиента / Название компании"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="holding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surveys.holding",
                verbose_name="Холдинг",
            ),
        ),
    ]
