# Generated by Django 5.2.8 on 2025-11-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_holding_client_employee_alter_client_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_reports/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('detected_address', models.CharField(blank=True, max_length=500)),
                ('is_high_quality', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.employee'),
        ),
        migrations.AlterField(
            model_name='client',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.holding'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текст'), ('single_select', 'Список (один выбор)'), ('multi_select', 'Список (множественный выбор)'), ('checkbox', 'Чекбоксы (множественный)'), ('radio', 'Радиокнопки (один)'), ('photo', 'Фото')], max_length=20),
        ),
        migrations.CreateModel(
            name='ModeratorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.employee')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='surveys.photo')),
            ],
            options={
                'verbose_name': 'Комментарий модератора',
                'verbose_name_plural': 'Комментарии модератора',
            },
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_count', models.PositiveIntegerField(verbose_name='Количество стендов')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('rejected', 'На доработку'), ('approved', 'Принят')], default='draft', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, verbose_name='Комментарий при возврате')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.employee', verbose_name='Сотрудник')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='surveys.employee')),
            ],
            options={
                'verbose_name': 'Фотоотчёт',
                'verbose_name_plural': 'Фотоотчёты',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='surveys.photoreport'),
        ),
    ]
