# Generated by Django 5.2.8 on 2025-11-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_photo_alter_client_employee_alter_client_holding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoreport",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reports",
                to="surveys.employee",
                verbose_name="Назначен сотруднику",
            ),
        ),
    ]
