# Generated by Django 5.2.8 on 2025-11-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_photoreport_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoreport",
            name="assignment_comment",
            field=models.TextField(
                blank=True, verbose_name="Комментарий при назначении"
            ),
        ),
    ]
