# Generated by Django 5.2.8 on 2025-11-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0006_photoreport_assignment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to="surveys.employee",
                verbose_name="Создано",
            ),
        ),
    ]
